package com.example.backend.model.domain;

public enum MessageType {
    APPLICATION_SUBMITTED,
    APPROVAL_RETURNED,
    APPROVAL_REJECTED,
    APPROVAL_APPROVED,
    APPROVAL_PENDING,
    APPROVAL_CANCELLED,
    BATCH_DEADLINE,
    OFFLINE_PROCESSING
}
