DROP TABLE IF EXISTS message_read_record;
DROP TABLE IF EXISTS system_message;
DROP TABLE IF EXISTS approval_submission_record;
DROP TABLE IF EXISTS approval_record;
DROP TABLE IF EXISTS sys_user;
DROP TABLE IF EXISTS gift_application_item;
DROP TABLE IF EXISTS gift_application;
DROP TABLE IF EXISTS subsidy_application;
DROP TABLE IF EXISTS batch_gift_item;
DROP TABLE IF EXISTS college_gift_quota;
DROP TABLE IF EXISTS grade_gift_quota;
DROP TABLE IF EXISTS college_subsidy_quota;
DROP TABLE IF EXISTS grade_subsidy_quota;
DROP TABLE IF EXISTS gift_item;

-- PasswordMigrationRunner is active in the application context used by tests.
-- The empty table lets the runner execute without coupling tests to local MySQL.
CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_name VARCHAR(100),
    password VARCHAR(255),
    last_login_time TIMESTAMP,
    remark VARCHAR(500),
    deleted BIGINT NOT NULL DEFAULT 0,
    gmt_created TIMESTAMP,
    gmt_modified TIMESTAMP
);

CREATE TABLE approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    review_round INT NOT NULL CHECK (review_round >= 0),
    approval_level VARCHAR(32) NOT NULL,
    approver_id BIGINT,
    approver_name_snapshot VARCHAR(100),
    action VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    old_status VARCHAR(32) NOT NULL,
    new_status VARCHAR(32) NOT NULL,
    modified_fields JSON,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_submission_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_type VARCHAR(32) NOT NULL,
    green_channel_batch_id BIGINT,
    subsidy_batch_id BIGINT,
    submission_level VARCHAR(32) NOT NULL,
    submission_type VARCHAR(32) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL DEFAULT 0,
    review_round INT NOT NULL DEFAULT 0 CHECK (review_round >= 0),
    submitter_id BIGINT NOT NULL,
    submitted_count INT NOT NULL DEFAULT 0 CHECK (submitted_count >= 0),
    status VARCHAR(32) NOT NULL,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    submit_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_submission_batch_reference CHECK (
        (batch_type = 'GREEN_CHANNEL' AND green_channel_batch_id IS NOT NULL AND subsidy_batch_id IS NULL)
        OR
        (batch_type = 'SUBSIDY' AND green_channel_batch_id IS NULL AND subsidy_batch_id IS NOT NULL)
    ),
    CONSTRAINT uk_submission_green_scope UNIQUE (
        green_channel_batch_id, submission_level, scope_id,
        submission_type, application_id, review_round
    ),
    CONSTRAINT uk_submission_subsidy_scope UNIQUE (
        subsidy_batch_id, submission_level, scope_id,
        submission_type, application_id, review_round
    )
);

CREATE TABLE system_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL,
    message_type VARCHAR(32) NOT NULL,
    business_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message_read_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_message_read UNIQUE (message_id, user_id)
);

-- 成员二资源与明细表：供 Mapper H2 集成测试使用。
CREATE TABLE gift_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE batch_gift_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    gift_item_id BIGINT NOT NULL,
    stock_total INT NOT NULL,
    reserved_count INT NOT NULL DEFAULT 0,
    used_count INT NOT NULL DEFAULT 0,
    per_student_limit INT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE gift_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE gift_application_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_application_id BIGINT NOT NULL,
    batch_gift_item_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE subsidy_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    expected_amount DECIMAL(12,2) NOT NULL,
    final_amount DECIMAL(12,2),
    deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE college_gift_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, college_id BIGINT NOT NULL, quota_total INT NOT NULL,
    reserved_count INT NOT NULL DEFAULT 0, used_count INT NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 0, deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE grade_gift_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, grade_id BIGINT NOT NULL, quota_total INT NOT NULL,
    reserved_count INT NOT NULL DEFAULT 0, used_count INT NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 0, deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE college_subsidy_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, college_id BIGINT NOT NULL, quota_amount DECIMAL(12,2) NOT NULL,
    reserved_amount DECIMAL(12,2) NOT NULL DEFAULT 0, used_amount DECIMAL(12,2) NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 0, deleted BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE grade_subsidy_quota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL, grade_id BIGINT NOT NULL, quota_amount DECIMAL(12,2) NOT NULL,
    reserved_amount DECIMAL(12,2) NOT NULL DEFAULT 0, used_amount DECIMAL(12,2) NOT NULL DEFAULT 0, version INT NOT NULL DEFAULT 0, deleted BIGINT NOT NULL DEFAULT 0
);
