DROP TABLE IF EXISTS message_read_record;
DROP TABLE IF EXISTS system_message;
DROP TABLE IF EXISTS approval_submission_record;
DROP TABLE IF EXISTS approval_record;

CREATE TABLE approval_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    review_round INT NOT NULL CHECK (review_round >= 0),
    approval_level VARCHAR(32) NOT NULL,
    approver_id BIGINT,
    approver_name_snapshot VARCHAR(100),
    action VARCHAR(32) NOT NULL,
    comment VARCHAR(1000),
    old_status VARCHAR(32) NOT NULL,
    new_status VARCHAR(32) NOT NULL,
    modified_fields JSON,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE approval_submission_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_type VARCHAR(32) NOT NULL,
    green_channel_batch_id BIGINT,
    subsidy_batch_id BIGINT,
    submission_level VARCHAR(32) NOT NULL,
    submission_type VARCHAR(32) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL DEFAULT 0,
    review_round INT NOT NULL DEFAULT 0 CHECK (review_round >= 0),
    submitter_id BIGINT NOT NULL,
    submitted_count INT NOT NULL DEFAULT 0 CHECK (submitted_count >= 0),
    status VARCHAR(32) NOT NULL,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    submit_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_submission_batch_reference CHECK (
        (batch_type = 'GREEN_CHANNEL' AND green_channel_batch_id IS NOT NULL AND subsidy_batch_id IS NULL)
        OR
        (batch_type = 'SUBSIDY' AND green_channel_batch_id IS NULL AND subsidy_batch_id IS NOT NULL)
    ),
    CONSTRAINT uk_submission_green_scope UNIQUE (
        green_channel_batch_id, submission_level, scope_id,
        submission_type, application_id, review_round
    ),
    CONSTRAINT uk_submission_subsidy_scope UNIQUE (
        subsidy_batch_id, submission_level, scope_id,
        submission_type, application_id, review_round
    )
);

CREATE TABLE system_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL,
    message_type VARCHAR(32) NOT NULL,
    business_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message_read_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_message_read UNIQUE (message_id, user_id)
);
