package com.example.backend.approval.domain;

public enum ApprovalErrorCode {
    APPROVAL_INVALID_STATUS,
    APPROVAL_FORBIDDEN_SCOPE,
    APPROVAL_ACTION_REQUIRED,
    APPROVAL_COMMENT_REQUIRED,
    APPROVAL_ALREADY_PROCESSED,
    APPROVAL_VERSION_CONFLICT,
    APPROVAL_UNREVIEWED_EXISTS,
    APPROVAL_BATCH_NOT_CLOSED,
    APPROVAL_BATCH_ALREADY_SUBMITTED,
    APPROVAL_COLLEGE_DEADLINE_EXPIRED,
    APPROVAL_QUOTA_INSUFFICIENT,
    APPROVAL_CANCEL_NOT_ALLOWED,
    APPROVAL_RESOURCE_ROLLBACK_FAILED
}
