<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Refresh } from '@element-plus/icons-vue'
import AllocationDialog from '../components/application/AllocationDialog.vue'
import SubsidyBatchConfig from '../components/application/SubsidyBatchConfig.vue'
import SubsidyQuotaConfig from '../components/application/SubsidyQuotaConfig.vue'
import { batchAPI, catalogAPI, policyRuleAPI, resourceConfigAPI } from '../api/application.js'
import { formatBatchLabel } from '../constants/batch.js'

const activeTab = ref('batch'); const loading = ref(false); const resourceLoading = ref(false)
const fees = ref([]); const amounts = ref([]); const gifts = ref([]); const colleges = ref([]); const grades = ref([]); const batches = ref([]); const policies = ref([])
const resourceBatchId = ref(null); const batchGiftItems = ref([]); const giftQuotas = ref([]); const subsidyQuotas = ref([])
const feeDialog = ref(false); const amountDialog = ref(false); const giftDialog = ref(false); const batchDialog = ref(false); const batchGiftDialog = ref(false); const allocationOpen = ref(false); const mergeFeeDialog = ref(false); const policyDialog = ref(false)
const editingId = ref(null); const editingBatchGift = ref(null); const editingAllocation = ref(null)
const mergingFee = ref(null); const mergeTargetId = ref(null)
const feeForm = reactive({ name: '', enabled: true }); const amountForm = reactive({ feeItemId: null, amount: null, enabled: true }); const giftForm = reactive({ name: '', enabled: true, imageUrl: '', itemType: '', itemSize: '', description: '', unitPrice: 0, genderRestriction: 'ALL', required: false })
const batchForm = reactive({ batchCode: '', batchName: '', academicYear: '', startTime: '', endTime: '', collegeDeadline: '', status: 'DRAFT', remark: '', eligibleGradeIds: [], fundingSourceCodes: ['SCHOOL'] })
const policyForm = reactive({ ruleCode: '', ruleName: '', ruleContent: '', batchType: 'GREEN_CHANNEL', sortOrder: 0, enabled: true })
const batchGiftForm = reactive({ giftItemId: null, stockTotal: null, perStudentLimit: 1, version: null })
const feeOptions = computed(() => fees.value.filter(item => item.enabled)); const giftOptions = computed(() => gifts.value.filter(item => item.enabled))
function errorMessage(error, fallback = '操作失败') { return error.response?.data?.message || error.message || fallback }
function resetEditing() { editingId.value = null }
async function loadData() {
  loading.value = true
  try {
    const [feeData, amountData, giftData, collegeData, gradeData, batchData, policyData] = await Promise.all([catalogAPI.listFeeItems(), catalogAPI.listFeeAmountOptions(), catalogAPI.listGiftItems(), resourceConfigAPI.colleges(), resourceConfigAPI.grades(), batchAPI.listGreenChannel(), policyRuleAPI.list()])
    fees.value = feeData || []; amounts.value = amountData || []; gifts.value = giftData || []; colleges.value = collegeData || []; grades.value = gradeData || []; batches.value = batchData || []; policies.value = policyData || []
    if (!resourceBatchId.value && batches.value.length) resourceBatchId.value = batches.value[0].id
    if (resourceBatchId.value) await loadResources()
  } catch (error) { ElMessage.error(errorMessage(error, '配置数据加载失败')) } finally { loading.value = false }
}
async function loadResources() {
  if (!resourceBatchId.value) return ElMessage.warning('请选择需要配置的申请批次')
  resourceLoading.value = true
  try {
    const [items, collegeGift, gradeGift] = await Promise.all([
      resourceConfigAPI.batchGiftItems(resourceBatchId.value), resourceConfigAPI.giftQuotas(resourceBatchId.value, 'COLLEGE'), resourceConfigAPI.giftQuotas(resourceBatchId.value, 'GRADE'),
    ])
    batchGiftItems.value = items || []
    giftQuotas.value = [...(collegeGift || []), ...(gradeGift || [])].map(item => ({ ...item, resource: 'GIFT' }))
    subsidyQuotas.value = []
  } catch (error) { batchGiftItems.value = []; giftQuotas.value = []; subsidyQuotas.value = []; ElMessage.error(errorMessage(error, '资源配置加载失败')) } finally { resourceLoading.value = false }
}
function openFee(row) { resetEditing(); editingId.value = row?.id ?? null; Object.assign(feeForm, row ? { name: row.name, enabled: row.enabled } : { name: '', enabled: true }); feeDialog.value = true }
function openFeeMerge(row) { mergingFee.value = row; mergeTargetId.value = feeOptions.value.find(item => item.id !== row.id)?.id ?? null; mergeFeeDialog.value = true }
function openAmount(row) { resetEditing(); editingId.value = row?.id ?? null; Object.assign(amountForm, row ? { feeItemId: row.feeItemId, amount: row.amount, enabled: row.enabled } : { feeItemId: feeOptions.value[0]?.id ?? null, amount: null, enabled: true }); amountDialog.value = true }
function openGift(row) { resetEditing(); editingId.value = row?.id ?? null; Object.assign(giftForm, row ? { name: row.name, enabled: row.enabled, imageUrl: row.imageUrl || '', itemType: row.itemType || '', itemSize: row.itemSize || '', description: row.description || '', unitPrice: Number(row.unitPrice || 0), genderRestriction: row.genderRestriction || 'ALL', required: !!row.required } : { name: '', enabled: true, imageUrl: '', itemType: '', itemSize: '', description: '', unitPrice: 0, genderRestriction: 'ALL', required: false }); giftDialog.value = true }
function openBatch(row) { editingId.value = row?.id ?? null; Object.assign(batchForm, row ? { batchCode: row.batchCode, batchName: row.batchName, academicYear: row.academicYear || '', startTime: row.startTime, endTime: row.endTime, collegeDeadline: row.collegeDeadline, status: row.status, remark: row.remark || '', eligibleGradeIds: row.eligibleGradeIds || [], fundingSourceCodes: row.fundingSourceCodes || [] } : { batchCode: '', batchName: '', academicYear: `${new Date().getFullYear()}-${new Date().getFullYear() + 1}`, startTime: '', endTime: '', collegeDeadline: '', status: 'DRAFT', remark: '', eligibleGradeIds: [], fundingSourceCodes: ['SCHOOL'] }); batchDialog.value = true }
function openPolicy(row) { editingId.value = row?.id ?? null; Object.assign(policyForm, row ? { ruleCode: row.ruleCode, ruleName: row.ruleName, ruleContent: row.ruleContent, batchType: row.batchType, sortOrder: row.sortOrder, enabled: row.enabled } : { ruleCode: '', ruleName: '', ruleContent: '', batchType: 'GREEN_CHANNEL', sortOrder: 0, enabled: true }); policyDialog.value = true }
function openBatchGift(row) { editingBatchGift.value = row || null; Object.assign(batchGiftForm, row ? { giftItemId: row.giftItemId, stockTotal: row.stockTotal, perStudentLimit: row.perStudentLimit, version: row.version } : { giftItemId: giftOptions.value[0]?.id ?? null, stockTotal: null, perStudentLimit: 1, version: null }); batchGiftDialog.value = true }
function openAllocation(row) { editingAllocation.value = row || null; allocationOpen.value = true }
async function saveFee() { try { if (!feeForm.name?.trim()) return ElMessage.warning('请输入欠费项目名称'); editingId.value ? await catalogAPI.updateFeeItem(editingId.value, feeForm) : await catalogAPI.createFeeItem(feeForm); ElMessage.success('欠费项目已保存'); feeDialog.value = false; loadData() } catch (error) { ElMessage.error(errorMessage(error)) } }
async function mergeFee() { try { if (!mergingFee.value || !mergeTargetId.value) return ElMessage.warning('请选择保留的欠费项目'); await catalogAPI.mergeFeeItem(mergingFee.value.id, mergeTargetId.value); ElMessage.success('欠费项目已合并，金额档位已同步迁移'); mergeFeeDialog.value = false; await loadData() } catch (error) { ElMessage.error(errorMessage(error)) } }
async function saveAmount() { try { if (!amountForm.feeItemId || !amountForm.amount) return ElMessage.warning('请选择项目并填写金额'); editingId.value ? await catalogAPI.updateFeeAmountOption(editingId.value, amountForm) : await catalogAPI.createFeeAmountOption(amountForm); ElMessage.success('金额档位已保存'); amountDialog.value = false; loadData() } catch (error) { ElMessage.error(errorMessage(error)) } }
async function saveGift() { try { if (!giftForm.name?.trim()) return ElMessage.warning('请输入礼包物品名称'); editingId.value ? await catalogAPI.updateGiftItem(editingId.value, giftForm) : await catalogAPI.createGiftItem(giftForm); ElMessage.success('礼包物品已保存'); giftDialog.value = false; loadData() } catch (error) { ElMessage.error(errorMessage(error)) } }
async function saveBatch() { try { if (!batchForm.batchCode?.trim() || !batchForm.batchName?.trim() || !batchForm.academicYear?.trim()) return ElMessage.warning('请完整填写批次编号、名称和学年'); if (!batchForm.startTime || !batchForm.endTime || !batchForm.collegeDeadline) return ElMessage.warning('请完整填写三个时间节点'); if (!batchForm.eligibleGradeIds.length) return ElMessage.warning('请至少选择一个适用年级'); if (!batchForm.fundingSourceCodes.length) return ElMessage.warning('请至少选择一个资金来源'); const data = { ...batchForm }; editingId.value ? await batchAPI.updateGreenChannel(editingId.value, data) : await batchAPI.createGreenChannel(data); ElMessage.success('绿色通道信息已保存'); batchDialog.value = false; await loadData() } catch (error) { ElMessage.error(errorMessage(error, '批次保存失败')) } }
async function savePolicy() { try { if (!policyForm.ruleCode?.trim() || !policyForm.ruleName?.trim() || !policyForm.ruleContent?.trim()) return ElMessage.warning('请完整填写规则编码、名称和引导文案'); const data = { ...policyForm }; editingId.value ? await policyRuleAPI.update(editingId.value, data) : await policyRuleAPI.create(data); ElMessage.success('政策引导已保存'); policyDialog.value = false; await loadData() } catch (error) { ElMessage.error(errorMessage(error, '政策引导保存失败')) } }
async function toggleBatch(row) { try { await batchAPI.toggleGreenChannel(row.id); ElMessage.success(row.enabled ? '批次已停用' : '批次已启用'); await loadData() } catch (error) { ElMessage.error(errorMessage(error, '状态切换失败')) } }
async function saveBatchGift() { try { if (!resourceBatchId.value || !batchGiftForm.giftItemId || batchGiftForm.stockTotal === null) return ElMessage.warning('请选择批次、物品并填写库存'); if (editingBatchGift.value) await resourceConfigAPI.updateBatchGiftItem(editingBatchGift.value.id, { stockTotal: batchGiftForm.stockTotal, perStudentLimit: batchGiftForm.perStudentLimit, version: batchGiftForm.version }); else await resourceConfigAPI.createBatchGiftItem({ batchId: resourceBatchId.value, giftItemId: batchGiftForm.giftItemId, stockTotal: batchGiftForm.stockTotal, perStudentLimit: batchGiftForm.perStudentLimit }); ElMessage.success('批次礼包配置已保存'); batchGiftDialog.value = false; loadResources() } catch (error) { ElMessage.error(errorMessage(error)) } }
async function remove(kind, row) {
  try { await ElMessageBox.confirm(`确认删除“${row.name || row.giftItemName || row.targetName || `¥${row.amount}`}”吗？`, '删除确认', { type: 'warning' });
    if (kind === 'fee') await catalogAPI.deleteFeeItem(row.id); if (kind === 'amount') await catalogAPI.deleteFeeAmountOption(row.id); if (kind === 'gift') await catalogAPI.deleteGiftItem(row.id); if (kind === 'policy') await policyRuleAPI.delete(row.id); if (kind === 'batchGift') await resourceConfigAPI.deleteBatchGiftItem(row.id); if (kind === 'giftQuota') await resourceConfigAPI.deleteGiftQuota(row.id, row.scope); if (kind === 'subsidyQuota') await resourceConfigAPI.deleteSubsidyQuota(row.id, row.scope)
    ElMessage.success('已删除'); if (['fee','amount','gift','policy'].includes(kind)) loadData(); else loadResources()
  } catch (error) { if (error !== 'cancel') ElMessage.error(errorMessage(error)) }
}
function feeName(id) { return fees.value.find(item => item.id === id)?.name || `项目 #${id}` }
function remaining(row, resource) { return resource === 'GIFT' ? row.quotaTotal - row.reservedCount : Number(row.quotaAmount) - Number(row.reservedAmount) }
function gradeName(id) { return grades.value.find(item => item.id === id)?.gradeName || grades.value.find(item => item.id === id)?.name || `年级 #${id}` }
function fundingName(code) { return ({ SCHOOL: '学校专项', GOVERNMENT: '政府资助', SOCIETY: '社会捐助', OTHER: '其他来源' })[code] || code }
onMounted(loadData)
</script>

<template>
  <div class="page-container config-page">
    <section class="page-heading-row"><div><h1>绿色通道信息设置</h1><p>统一维护申请时间、学年、资金来源、适用范围、欠费项目、礼包库存与额度。</p></div><div class="page-actions"><el-button @click="loadData"><el-icon><Refresh /></el-icon>刷新</el-button></div></section>
    <section class="content-card config-card" v-loading="loading"><el-tabs v-model="activeTab" class="config-tabs">
      <el-tab-pane label="批次设置" name="batch"><div class="config-toolbar"><span>批次开放后，符合适用年级且处于申请时间内的学生才可选择。</span><el-button type="primary" @click="openBatch()"><el-icon><Plus /></el-icon>新增批次</el-button></div><el-table :data="batches" border class="standard-table" empty-text="暂无绿色通道批次"><el-table-column prop="batchCode" label="批次编号" min-width="130"/><el-table-column prop="batchName" label="批次名称" min-width="170"/><el-table-column prop="academicYear" label="学年" width="110"/><el-table-column label="申请时间" min-width="220"><template #default="{row}">{{ String(row.startTime).replace('T',' ') }}<br/>至 {{ String(row.endTime).replace('T',' ') }}</template></el-table-column><el-table-column label="资金来源" min-width="170"><template #default="{row}">{{ (row.fundingSourceCodes || []).map(fundingName).join('、') || '—' }}</template></el-table-column><el-table-column label="适用年级" min-width="180"><template #default="{row}">{{ (row.eligibleGradeIds || []).map(gradeName).join('、') || '—' }}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.status === 'OPEN' && row.enabled ? 'success' : 'info'">{{ !row.enabled ? '已停用' : ({DRAFT:'草稿',OPEN:'开放',CLOSED:'关闭'})[row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="openBatch(row)">编辑</el-button><el-button link :type="row.enabled ? 'warning' : 'success'" @click="toggleBatch(row)">{{ row.enabled ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="补助批次设置" name="subsidy-batch"><SubsidyBatchConfig/></el-tab-pane>
      <el-tab-pane label="政策引导" name="policy"><div class="config-toolbar"><span>学生填写申请时展示启用的政策说明和材料提示。</span><el-button type="primary" @click="openPolicy()"><el-icon><Plus /></el-icon>新增政策引导</el-button></div><el-table :data="policies" border class="standard-table" empty-text="暂无政策引导"><el-table-column prop="ruleCode" label="规则编码" width="150"/><el-table-column prop="ruleName" label="规则名称" width="180"/><el-table-column prop="ruleContent" label="引导文案" min-width="300" show-overflow-tooltip/><el-table-column prop="batchType" label="适用类型" width="160"/><el-table-column prop="sortOrder" label="排序" width="80"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openPolicy(row)">编辑</el-button><el-button link type="danger" @click="remove('policy',row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="欠费配置" name="fees"><div class="config-toolbar"><span>学生端总申报金额由后端限制为不超过 ¥8,000。</span><div><el-button @click="openAmount()">新增金额档位</el-button><el-button type="primary" @click="openFee()"><el-icon><Plus /></el-icon>新增欠费项目</el-button></div></div><el-table :data="fees" border class="standard-table" empty-text="暂无欠费项目"><el-table-column prop="name" label="欠费项目"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="190"><template #default="{row}"><el-button link type="primary" @click="openFee(row)">编辑</el-button><el-button link type="warning" :disabled="fees.length < 2" @click="openFeeMerge(row)">合并</el-button><el-button link type="danger" @click="remove('fee',row)">删除</el-button></template></el-table-column></el-table><h2 class="subsection-title">金额档位</h2><el-table :data="amounts" border class="standard-table" empty-text="暂无金额档位"><el-table-column label="欠费项目"><template #default="{row}">{{ feeName(row.feeItemId) }}</template></el-table-column><el-table-column label="金额"><template #default="{row}">¥{{ Number(row.amount).toFixed(2) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openAmount(row)">编辑</el-button><el-button link type="danger" @click="remove('amount',row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="礼包配置" name="gifts"><div class="config-toolbar"><span>先维护物品目录，再按批次配置库存和单人上限。</span><el-button type="primary" @click="openGift()"><el-icon><Plus /></el-icon>新增礼包物品</el-button></div><el-table :data="gifts" border class="standard-table" empty-text="暂无礼包物品"><el-table-column prop="name" label="物品名称"/><el-table-column prop="itemType" label="类别"/><el-table-column prop="itemSize" label="规格"/><el-table-column label="单价"><template #default="{row}">¥{{ Number(row.unitPrice || 0).toFixed(2) }}</template></el-table-column><el-table-column label="适用性别"><template #default="{row}">{{ ({ALL:'不限',MALE:'男',FEMALE:'女'})[row.genderRestriction] || '不限' }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled ? 'success' : 'info'">{{ row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openGift(row)">编辑</el-button><el-button link type="danger" @click="remove('gift',row)">删除</el-button></template></el-table-column></el-table><div class="resource-heading"><el-select v-model="resourceBatchId" placeholder="请选择批次" style="width:320px"><el-option v-for="batch in batches" :key="batch.id" :label="formatBatchLabel(batch)" :value="batch.id"/></el-select><el-button @click="loadResources">加载批次资源</el-button><el-button type="primary" :disabled="!resourceBatchId" @click="openBatchGift()">配置批次物品</el-button></div><el-table v-loading="resourceLoading" :data="batchGiftItems" border class="standard-table" empty-text="请加载批次资源"><el-table-column prop="giftItemName" label="物品"/><el-table-column prop="stockTotal" label="库存"/><el-table-column prop="reservedCount" label="已预占"/><el-table-column prop="usedCount" label="已使用"/><el-table-column prop="perStudentLimit" label="单人上限"/><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openBatchGift(row)">编辑</el-button><el-button link type="danger" @click="remove('batchGift',row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="名额与补助额度" name="quota"><div class="resource-heading"><el-select v-model="resourceBatchId" placeholder="请选择批次" style="width:320px"><el-option v-for="batch in batches" :key="batch.id" :label="formatBatchLabel(batch)" :value="batch.id"/></el-select><el-button @click="loadResources">加载资源</el-button><el-button type="primary" :disabled="!resourceBatchId" @click="openAllocation()">新增分配</el-button></div><h2 class="subsection-title">礼包名额</h2><el-table v-loading="resourceLoading" :data="giftQuotas" border class="standard-table" empty-text="请加载批次资源"><el-table-column prop="scope" label="维度" width="100"><template #default="{row}">{{ row.scope === 'COLLEGE' ? '学院' : '年级' }}</template></el-table-column><el-table-column prop="targetName" label="对象"/><el-table-column prop="quotaTotal" label="总名额"/><el-table-column prop="reservedCount" label="预占"/><el-table-column prop="usedCount" label="已使用"/><el-table-column label="剩余"><template #default="{row}">{{ remaining(row,'GIFT') }}</template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openAllocation(row)">编辑</el-button><el-button link type="danger" @click="remove('giftQuota',row)">删除</el-button></template></el-table-column></el-table><h2 class="subsection-title">生活 / 路费补助额度</h2><el-table v-loading="resourceLoading" :data="subsidyQuotas" border class="standard-table" empty-text="请加载批次资源"><el-table-column prop="scope" label="维度" width="100"><template #default="{row}">{{ row.scope === 'COLLEGE' ? '学院' : '年级' }}</template></el-table-column><el-table-column prop="targetName" label="对象"/><el-table-column label="总额度"><template #default="{row}">¥{{ Number(row.quotaAmount).toFixed(2) }}</template></el-table-column><el-table-column label="预占"><template #default="{row}">¥{{ Number(row.reservedAmount).toFixed(2) }}</template></el-table-column><el-table-column label="已使用"><template #default="{row}">¥{{ Number(row.usedAmount).toFixed(2) }}</template></el-table-column><el-table-column label="剩余"><template #default="{row}">¥{{ Number(remaining(row,'SUBSIDY')).toFixed(2) }}</template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="openAllocation(row)">编辑</el-button><el-button link type="danger" @click="remove('subsidyQuota',row)">删除</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs><SubsidyQuotaConfig v-if="activeTab === 'gifts'"/></section>
    <el-dialog v-model="feeDialog" :title="editingId ? '编辑欠费项目' : '新增欠费项目'" width="480px"><el-form label-width="90px"><el-form-item label="项目名称" required><el-input v-model="feeForm.name" maxlength="64"/></el-form-item><el-form-item label="启用"><el-switch v-model="feeForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="feeDialog=false">取消</el-button><el-button type="primary" @click="saveFee">保存</el-button></template></el-dialog>
    <el-dialog v-model="mergeFeeDialog" title="合并欠费项目" width="520px"><el-alert type="warning" :closable="false" show-icon title="合并后将保留目标项目，并迁移不重复的金额档位。已被申请引用的项目不能合并。"/><el-form label-width="110px" class="merge-fee-form"><el-form-item label="待合并项目"><el-input :model-value="mergingFee?.name" disabled/></el-form-item><el-form-item label="保留项目" required><el-select v-model="mergeTargetId"><el-option v-for="item in feeOptions.filter(item => item.id !== mergingFee?.id)" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="mergeFeeDialog=false">取消</el-button><el-button type="primary" @click="mergeFee">确认合并</el-button></template></el-dialog>
    <el-dialog v-model="amountDialog" :title="editingId ? '编辑金额档位' : '新增金额档位'" width="480px"><el-form label-width="90px"><el-form-item label="欠费项目" required><el-select v-model="amountForm.feeItemId"><el-option v-for="item in feeOptions" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="金额" required><el-input-number v-model="amountForm.amount" :min="0.01" :precision="2" :step="100"/></el-form-item><el-form-item label="启用"><el-switch v-model="amountForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="amountDialog=false">取消</el-button><el-button type="primary" @click="saveAmount">保存</el-button></template></el-dialog>
    <el-dialog v-model="giftDialog" :title="editingId ? '编辑礼包物品' : '新增礼包物品'" width="620px"><el-form label-width="100px"><el-form-item label="物品名称" required><el-input v-model="giftForm.name" maxlength="64"/></el-form-item><el-form-item label="物品类别"><el-input v-model="giftForm.itemType" maxlength="32" placeholder="如：生活用品"/></el-form-item><el-form-item label="规格尺寸"><el-input v-model="giftForm.itemSize" maxlength="32" placeholder="如：均码 / 500ml"/></el-form-item><el-form-item label="物品图片"><el-input v-model="giftForm.imageUrl" placeholder="图片 URL"/></el-form-item><el-form-item label="参考单价"><el-input-number v-model="giftForm.unitPrice" :min="0" :precision="2"/></el-form-item><el-form-item label="适用性别"><el-select v-model="giftForm.genderRestriction"><el-option label="不限" value="ALL"/><el-option label="男" value="MALE"/><el-option label="女" value="FEMALE"/></el-select></el-form-item><el-form-item label="物品说明"><el-input v-model="giftForm.description" type="textarea" :rows="3" maxlength="255"/></el-form-item><el-form-item label="必选物品"><el-switch v-model="giftForm.required"/></el-form-item><el-form-item label="启用"><el-switch v-model="giftForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="giftDialog=false">取消</el-button><el-button type="primary" @click="saveGift">保存</el-button></template></el-dialog>
    <el-dialog v-model="batchDialog" :title="editingId ? '编辑绿色通道批次' : '新增绿色通道批次'" width="720px"><el-form label-width="120px"><el-form-item label="批次编号" required><el-input v-model="batchForm.batchCode" :disabled="!!editingId" maxlength="32"/></el-form-item><el-form-item label="批次名称" required><el-input v-model="batchForm.batchName" maxlength="64"/></el-form-item><el-form-item label="学年" required><el-input v-model="batchForm.academicYear" maxlength="16" placeholder="2026-2027"/></el-form-item><el-form-item label="申请开始时间" required><el-date-picker v-model="batchForm.startTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="申请截止时间" required><el-date-picker v-model="batchForm.endTime" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="学院上报截止" required><el-date-picker v-model="batchForm.collegeDeadline" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="资金来源" required><el-checkbox-group v-model="batchForm.fundingSourceCodes"><el-checkbox value="SCHOOL">学校专项</el-checkbox><el-checkbox value="GOVERNMENT">政府资助</el-checkbox><el-checkbox value="SOCIETY">社会捐助</el-checkbox><el-checkbox value="OTHER">其他来源</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="适用年级" required><el-select v-model="batchForm.eligibleGradeIds" multiple collapse-tags style="width:100%"><el-option v-for="grade in grades" :key="grade.id" :label="grade.gradeName || grade.name" :value="grade.id"/></el-select></el-form-item><el-form-item label="批次状态"><el-radio-group v-model="batchForm.status"><el-radio value="DRAFT">草稿</el-radio><el-radio value="OPEN">开放申请</el-radio><el-radio value="CLOSED">已关闭</el-radio></el-radio-group></el-form-item><el-form-item label="备注"><el-input v-model="batchForm.remark" type="textarea" :rows="3" maxlength="255"/></el-form-item></el-form><template #footer><el-button @click="batchDialog=false">取消</el-button><el-button type="primary" @click="saveBatch">保存</el-button></template></el-dialog>
    <el-dialog v-model="policyDialog" :title="editingId ? '编辑政策引导' : '新增政策引导'" width="660px"><el-form label-width="100px"><el-form-item label="规则编码" required><el-input v-model="policyForm.ruleCode" maxlength="32"/></el-form-item><el-form-item label="规则名称" required><el-input v-model="policyForm.ruleName" maxlength="64"/></el-form-item><el-form-item label="适用类型" required><el-select v-model="policyForm.batchType" style="width:100%"><el-option label="全部申请" value="ALL"/><el-option label="绿色通道" value="GREEN_CHANNEL"/><el-option label="生活补助" value="LIVING_SUBSIDY"/><el-option label="路费补助" value="TRAVEL_SUBSIDY"/></el-select></el-form-item><el-form-item label="排序"><el-input-number v-model="policyForm.sortOrder" :min="0" :precision="0"/></el-form-item><el-form-item label="引导文案" required><el-input v-model="policyForm.ruleContent" type="textarea" :rows="5" maxlength="2000" show-word-limit/></el-form-item><el-form-item label="启用"><el-switch v-model="policyForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="policyDialog=false">取消</el-button><el-button type="primary" @click="savePolicy">保存</el-button></template></el-dialog>
    <el-dialog v-model="batchGiftDialog" :title="editingBatchGift ? '编辑批次礼包物品' : '配置批次礼包物品'" width="480px"><el-form label-width="110px"><el-form-item label="礼包物品" required><el-select v-model="batchGiftForm.giftItemId" :disabled="!!editingBatchGift"><el-option v-for="item in giftOptions" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="库存总量" required><el-input-number v-model="batchGiftForm.stockTotal" :min="0" :precision="0"/></el-form-item><el-form-item label="单人上限" required><el-input-number v-model="batchGiftForm.perStudentLimit" :min="1" :precision="0"/></el-form-item></el-form><template #footer><el-button @click="batchGiftDialog=false">取消</el-button><el-button type="primary" @click="saveBatchGift">保存</el-button></template></el-dialog>
    <AllocationDialog v-model="allocationOpen" :batch-id="resourceBatchId" :colleges="colleges" :grades="grades" :editing="editingAllocation" @saved="loadResources"/>
  </div>
</template>

<style scoped>
.config-page { padding: 0 0 24px; }.config-tabs :deep(.el-tabs__header) { margin: 0; padding: 0 20px; }.config-tabs :deep(.el-tabs__content) { padding: 20px; }.config-toolbar,.resource-heading { margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center; gap: 12px; color: #6b7280; font-size: 12px; }.config-toolbar > div { display:flex; gap:12px; }.resource-heading { justify-content:flex-start; }.subsection-title { margin: 24px 0 12px; font-size:16px; }.merge-fee-form { margin-top: 20px; }
.config-tabs :deep(.el-tabs__item:first-child) { font-size:0; }.config-tabs :deep(.el-tabs__item:first-child::after) { content:'绿色通道批次'; font-size:14px; }
/* 欠费金额改为学生按实际情况填写，不再暴露维护成本高且易造成误解的预设金额档位。旧数据暂保留，确保历史申请可追溯。 */
.config-tabs :deep(.el-tab-pane:nth-child(4) > .config-toolbar .el-button:first-child),.config-tabs :deep(.el-tab-pane:nth-child(4) > .subsection-title),.config-tabs :deep(.el-tab-pane:nth-child(4) > .subsection-title + .el-table) { display:none; }
/* 生活、路费补助额度统一由申请资源页底部的补助额度配置维护，避免展示两套相同入口。 */
.config-tabs :deep(.el-tab-pane:nth-child(6) > .subsection-title:nth-of-type(2)),.config-tabs :deep(.el-tab-pane:nth-child(6) > .subsection-title:nth-of-type(2) + .el-table) { display:none; }
/* 所有配置表的最后一列均为操作列：覆盖全局按钮最小宽度，避免编辑/删除被挤成两行。 */
.config-page :deep(.standard-table .el-table__body .el-table__cell:last-child .cell) { display: flex; align-items: center; justify-content: center; gap: 8px; overflow: visible; }
.config-page :deep(.standard-table .el-table__body .el-table__cell:last-child .el-button) { min-width: 48px; height: 28px; margin-left: 0; padding: 0 6px; }
</style>
